import type { ApiCatalogEntry } from "@/lib/types";

export const apiCatalog: ApiCatalogEntry[] = [
  {
    id: "rest-countries",
    name: "REST Countries",
    category: "geography",
    description: "Country metadata, capital cities, regions, currencies, and flags.",
    authType: "none",
    baseUrl: "https://restcountries.com/v3.1",
    docsUrl: "https://restcountries.com/",
    inputs: ["country name", "region", "currency code"],
    outputs: ["country profile", "capital coordinates", "flag", "currency data"],
    tags: ["travel", "geo", "country", "reference", "planning"],
    sampleUseCases: ["Travel planners", "Market entry dashboards", "Localization tools"],
    difficulty: "easy",
    corsRisk: "low",
    rateLimitRisk: "low",
    frontendSafe: true,
    recommendedUsage: "Use as the geographic backbone for destination, policy, or regional dashboards.",
  },
  {
    id: "open-meteo",
    name: "Open-Meteo",
    category: "weather",
    description: "Free weather forecasts and climate data without API keys.",
    authType: "none",
    baseUrl: "https://api.open-meteo.com/v1",
    docsUrl: "https://open-meteo.com/",
    inputs: ["latitude", "longitude", "date range"],
    outputs: ["temperature", "rain chance", "wind", "daily forecast"],
    tags: ["weather", "forecast", "travel", "outdoor", "planning"],
    sampleUseCases: ["Trip planning", "Event readiness", "Climate insight tools"],
    difficulty: "easy",
    corsRisk: "low",
    rateLimitRisk: "low",
    frontendSafe: true,
    recommendedUsage: "Pair with location-aware APIs to add environment context to user decisions.",
  },
  {
    id: "frankfurter",
    name: "Frankfurter Currency API",
    category: "finance",
    description: "Exchange rates and lightweight currency conversion backed by ECB data.",
    authType: "none",
    baseUrl: "https://api.frankfurter.app",
    docsUrl: "https://www.frankfurter.app/docs/",
    inputs: ["base currency", "target currency", "amount"],
    outputs: ["converted totals", "exchange rate", "currency history"],
    tags: ["currency", "finance", "travel", "pricing", "budget"],
    sampleUseCases: ["Budget planners", "Cost comparison tools", "Global pricing widgets"],
    difficulty: "easy",
    corsRisk: "low",
    rateLimitRisk: "low",
    frontendSafe: true,
    recommendedUsage: "Add simple currency intelligence to planners, marketplaces, and dashboards.",
  },
  {
    id: "nasa-apod",
    name: "NASA APOD",
    category: "space",
    description: "Astronomy Picture of the Day and scientific media metadata.",
    authType: "optional",
    baseUrl: "https://api.nasa.gov/planetary",
    docsUrl: "https://api.nasa.gov/",
    inputs: ["date", "media type"],
    outputs: ["image", "astronomy explanation", "title", "copyright"],
    tags: ["space", "education", "media", "science", "night-sky"],
    sampleUseCases: ["Space discovery apps", "Learning dashboards", "Stargazing planners"],
    difficulty: "easy",
    corsRisk: "medium",
    rateLimitRisk: "medium",
    frontendSafe: true,
    recommendedUsage: "Use the demo key server-side or allow users to paste their own key later for scale.",
  },
  {
    id: "pokeapi",
    name: "PokéAPI",
    category: "gaming",
    description: "Open Pokémon data covering creatures, moves, types, and evolutions.",
    authType: "none",
    baseUrl: "https://pokeapi.co/api/v2",
    docsUrl: "https://pokeapi.co/docs/v2",
    inputs: ["pokemon name", "type", "generation"],
    outputs: ["stats", "sprites", "abilities", "moves"],
    tags: ["game", "quiz", "fan", "battle", "character"],
    sampleUseCases: ["Fan experiences", "Battle simulators", "Gameified learning apps"],
    difficulty: "easy",
    corsRisk: "low",
    rateLimitRisk: "medium",
    frontendSafe: true,
    recommendedUsage: "Great for playful prototypes with recognizable entities and rich metadata.",
  },
  {
    id: "open-library",
    name: "Open Library",
    category: "education",
    description: "Book search, editions, authors, and reading metadata.",
    authType: "none",
    baseUrl: "https://openlibrary.org",
    docsUrl: "https://openlibrary.org/developers/api",
    inputs: ["title", "author", "subject"],
    outputs: ["book results", "covers", "subjects", "edition info"],
    tags: ["books", "education", "reading", "research", "catalog"],
    sampleUseCases: ["Reading lists", "Book recommendation apps", "Student portals"],
    difficulty: "easy",
    corsRisk: "low",
    rateLimitRisk: "low",
    frontendSafe: true,
    recommendedUsage: "Use for discovery-heavy educational or content curation products.",
  },
  {
    id: "jikan",
    name: "Jikan Anime API",
    category: "entertainment",
    description: "Community anime and manga data based on MyAnimeList content.",
    authType: "none",
    baseUrl: "https://api.jikan.moe/v4",
    docsUrl: "https://docs.api.jikan.moe/",
    inputs: ["title", "genre", "season"],
    outputs: ["anime listings", "scores", "characters", "trailers"],
    tags: ["anime", "media", "community", "entertainment", "discovery"],
    sampleUseCases: ["Watchlist planners", "Anime explorer tools", "Community dashboards"],
    difficulty: "medium",
    corsRisk: "medium",
    rateLimitRisk: "medium",
    frontendSafe: true,
    recommendedUsage: "Best for discovery experiences where fandom context is valuable.",
  },
  {
    id: "nager-date",
    name: "Nager.Date Public Holidays",
    category: "calendar",
    description: "Public holidays and long weekend data for many countries.",
    authType: "none",
    baseUrl: "https://date.nager.at/api/v3",
    docsUrl: "https://date.nager.at/Api",
    inputs: ["country code", "year"],
    outputs: ["holiday lists", "holiday types", "long weekends"],
    tags: ["calendar", "holiday", "travel", "planning", "workforce"],
    sampleUseCases: ["Trip timing", "HR dashboards", "Product launch calendars"],
    difficulty: "easy",
    corsRisk: "low",
    rateLimitRisk: "low",
    frontendSafe: true,
    recommendedUsage: "Add time-aware planning signals for travel or workforce products.",
  },
  {
    id: "github-rest",
    name: "GitHub REST API",
    category: "developer",
    description: "Repository, issue, pull request, and contributor data for public projects.",
    authType: "optional",
    baseUrl: "https://api.github.com",
    docsUrl: "https://docs.github.com/en/rest",
    inputs: ["owner", "repo", "topic"],
    outputs: ["repo stats", "issues", "pull requests", "activity"],
    tags: ["developer", "oss", "analytics", "productivity", "market"],
    sampleUseCases: ["OSS dashboards", "Trend trackers", "Dev productivity tools"],
    difficulty: "medium",
    corsRisk: "medium",
    rateLimitRisk: "medium",
    frontendSafe: true,
    recommendedUsage: "Use unauthenticated public endpoints for demos, then add optional server auth later.",
  },
  {
    id: "hipolabs-universities",
    name: "Hipolabs Universities API",
    category: "education",
    description: "University listings grouped by country and domain.",
    authType: "none",
    baseUrl: "http://universities.hipolabs.com",
    docsUrl: "https://github.com/Hipo/university-domains-list-api",
    inputs: ["country", "name"],
    outputs: ["universities", "domains", "web pages"],
    tags: ["education", "university", "directory", "student", "research"],
    sampleUseCases: ["School explorers", "Student planning tools", "Higher-ed directories"],
    difficulty: "easy",
    corsRisk: "medium",
    rateLimitRisk: "low",
    frontendSafe: false,
    recommendedUsage: "Proxy this through a server route because the upstream is not consistently HTTPS-friendly.",
  },
  {
    id: "jokeapi",
    name: "JokeAPI",
    category: "entertainment",
    description: "Simple jokes API with category filtering and safe mode.",
    authType: "none",
    baseUrl: "https://v2.jokeapi.dev",
    docsUrl: "https://jokeapi.dev/",
    inputs: ["category", "safe mode"],
    outputs: ["setup", "delivery", "flags", "type"],
    tags: ["fun", "game", "quiz", "humor", "engagement"],
    sampleUseCases: ["Icebreakers", "Quiz mechanics", "Playful app moments"],
    difficulty: "easy",
    corsRisk: "low",
    rateLimitRisk: "low",
    frontendSafe: true,
    recommendedUsage: "Use as a delight layer to keep prototypes entertaining and sticky.",
  },
  {
    id: "coingecko",
    name: "CoinGecko Public API",
    category: "finance",
    description: "Crypto market prices, assets, and trend data.",
    authType: "none",
    baseUrl: "https://api.coingecko.com/api/v3",
    docsUrl: "https://docs.coingecko.com/reference/introduction",
    inputs: ["coin id", "vs currency", "market category"],
    outputs: ["price", "market cap", "rank", "market chart"],
    tags: ["crypto", "finance", "dashboard", "market", "signals"],
    sampleUseCases: ["Trading dashboards", "Market pulse apps", "Portfolio prototypes"],
    difficulty: "medium",
    corsRisk: "medium",
    rateLimitRisk: "medium",
    frontendSafe: true,
    recommendedUsage: "Keep requests server-side and cache aggressively for dashboard-style demos.",
  },
];

export const apiCatalogMap = Object.fromEntries(
  apiCatalog.map((api) => [api.id, api]),
) satisfies Record<string, ApiCatalogEntry>;
