import type { TemplatePreset } from "@/lib/types";

export const templatePresets: TemplatePreset[] = [
  {
    id: "dark-saas-dashboard",
    name: "Dark SaaS Dashboard",
    category: "dashboard",
    description: "Dense KPI layout with premium panels, charts, and operator controls.",
    bestForApiTags: ["finance", "dashboard", "developer", "analytics"],
    layout: ["Sticky left navigation", "Top-level KPI rail", "Split analytics panels"],
    colorSystem: ["Midnight navy", "Electric cyan", "Soft violet accents"],
    typography: ["Bold display headlines", "Compact UI labels", "Monospace for stats"],
    components: ["Metrics bar", "Command palette", "Panel tabs", "Line charts"],
    animationStyle: "Fast fade-ins with chart sweep transitions.",
    promptInstructions: "Prioritize high-density information design and keyboard-friendly workflows.",
  },
  {
    id: "minimal-startup-landing",
    name: "Minimal Startup Landing",
    category: "marketing",
    description: "Clean conversion-first product page for concept validation and MVP storytelling.",
    bestForApiTags: ["startup", "education", "developer", "planning"],
    layout: ["Hero spotlight", "Social proof band", "Feature stack", "CTA footer"],
    colorSystem: ["Carbon black", "White smoke", "Sky blue highlights"],
    typography: ["Large contrast headline", "Airy paragraph spacing", "Tight button labels"],
    components: ["Hero card", "Trust badges", "FAQ strip", "Pricing placeholder"],
    animationStyle: "Soft upward motion with understated hover transforms.",
    promptInstructions: "Keep sections sparse and persuasive with strong hierarchy and whitespace.",
  },
  {
    id: "ai-command-center",
    name: "AI Command Center",
    category: "operations",
    description: "Assistant-first control room with cards, prompts, and tactical status views.",
    bestForApiTags: ["developer", "analytics", "planning", "market"],
    layout: ["Three-column command shell", "Prompt panel", "Live feed modules"],
    colorSystem: ["Deep slate", "Neon teal", "Rose signal color"],
    typography: ["Operator-style labels", "Sharp metric numerals", "Readable body copy"],
    components: ["Prompt drawer", "Alert chips", "Action timeline", "Node canvas"],
    animationStyle: "Command-console glow pulses with layered parallax cards.",
    promptInstructions: "Emphasize orchestration, automation, and actionable insight surfaces.",
  },
  {
    id: "glassmorphism-dashboard",
    name: "Glassmorphism Dashboard",
    category: "dashboard",
    description: "Translucent cards, layered gradients, and polished executive UI.",
    bestForApiTags: ["travel", "finance", "weather", "education"],
    layout: ["Full-bleed background", "Floating panel grid", "Summary row"],
    colorSystem: ["Ink blue", "Ice cyan", "Iridescent purple"],
    typography: ["Smooth geometric headings", "Slim labels", "Readable metric stacks"],
    components: ["Floating widgets", "Gradient pills", "Progress arcs", "Map placeholder"],
    animationStyle: "Glass panels drift subtly with gradient shimmer transitions.",
    promptInstructions: "Use depth and layered surfaces without sacrificing readability.",
  },
  {
    id: "developer-tool-ui",
    name: "Developer Tool UI",
    category: "productivity",
    description: "Tooling-focused workspace with inspectors, logs, and side panels.",
    bestForApiTags: ["developer", "oss", "analytics", "market"],
    layout: ["Resizable panels", "Inspector sidebar", "Monospace consoles"],
    colorSystem: ["Graphite", "Emerald", "Signal amber"],
    typography: ["Code-friendly mono data", "Compact sans UI", "Strong section headers"],
    components: ["Log stream", "Filter bar", "Inspector tabs", "CLI prompt module"],
    animationStyle: "Minimal motion, mostly panel transitions and focus rings.",
    promptInstructions: "Optimize for clarity, state visibility, and power-user interactions.",
  },
  {
    id: "travel-planner-ui",
    name: "Travel Planner UI",
    category: "lifestyle",
    description: "Destination-first planner with weather, budget, and readiness widgets.",
    bestForApiTags: ["travel", "weather", "currency", "holiday"],
    layout: ["Destination hero", "Insights grid", "Checklist column", "Budget section"],
    colorSystem: ["Night sky", "Tropical cyan", "Sunrise amber"],
    typography: ["Friendly bold headings", "Readable body", "Metric emphasis"],
    components: ["Destination selector", "Weather card", "Budget converter", "Packing tips"],
    animationStyle: "Confident slide-ins with lively hover motion.",
    promptInstructions: "Create a planning experience that feels optimistic and actionable.",
  },
  {
    id: "crypto-finance-terminal",
    name: "Crypto Finance Terminal",
    category: "finance",
    description: "Market-heavy interface inspired by trading terminals and signal dashboards.",
    bestForApiTags: ["crypto", "finance", "market", "dashboard"],
    layout: ["High-density top rail", "Chart wall", "Signal table", "Trend column"],
    colorSystem: ["Obsidian", "Chart green", "Warning coral"],
    typography: ["Tabular numerals", "Narrow labels", "Bold headline totals"],
    components: ["Candlestick placeholder", "Ticker tape", "Heat map", "Trend list"],
    animationStyle: "Quick state flashes and animated metric counters.",
    promptInstructions: "Prioritize live-monitor feel and dense comparative information.",
  },
  {
    id: "education-portal",
    name: "Education Portal",
    category: "education",
    description: "Structured knowledge workspace for discovery, reading, and recommendations.",
    bestForApiTags: ["education", "books", "student", "research"],
    layout: ["Course-like dashboard", "Search shelf", "Insight sidebar", "Saved list rail"],
    colorSystem: ["Midnight ink", "Academic blue", "Warm parchment accent"],
    typography: ["Scholarly display", "Comfortable body", "Organized labels"],
    components: ["Reading queue", "Topic cards", "Recommendation chart", "Profile summary"],
    animationStyle: "Steady transitions with gentle content reveals.",
    promptInstructions: "Favor trust, structure, and thoughtful content pacing.",
  },
  {
    id: "fun-game-ui",
    name: "Fun Game UI",
    category: "gaming",
    description: "Playful interface with collectible cards, badge states, and animated rewards.",
    bestForApiTags: ["game", "quiz", "fun", "anime", "character"],
    layout: ["Stage area", "Card deck rail", "Score block", "Reward panel"],
    colorSystem: ["Deep purple", "Arcade cyan", "Candy magenta"],
    typography: ["Chunky display", "Readable support text", "Large score digits"],
    components: ["Battle cards", "Badge chips", "Progress tracker", "Reward toasts"],
    animationStyle: "Energetic bounces, quick sparks, and celebratory transitions.",
    promptInstructions: "Keep it playful without becoming visually chaotic.",
  },
  {
    id: "3d-hero-landing",
    name: "3D Hero Landing",
    category: "marketing",
    description: "Immersive landing experience with a lightweight 3D centerpiece and bold storytelling.",
    bestForApiTags: ["startup", "developer", "planning", "ai"],
    layout: ["Split hero", "Feature beam", "Orbit showcase", "CTA footer"],
    colorSystem: ["Space black", "Laser blue", "Aurora violet"],
    typography: ["Big cinematic headlines", "Tight captions", "Crisp CTA text"],
    components: ["3D hero object", "Orbit badges", "Feature tiles", "Demo teaser"],
    animationStyle: "Slow orbital motion with crisp reveal transitions.",
    promptInstructions: "Use 3D only as a focal accent and keep performance budget tight.",
  },
];

export const templatePresetMap = Object.fromEntries(
  templatePresets.map((template) => [template.id, template]),
) satisfies Record<string, TemplatePreset>;
